# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Serialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()


class NodeModel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNodeModel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NodeModel()
        x.Init(buf, n + offset)
        return x

    # NodeModel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NodeModel
    def RegistrationName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # NodeModel
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o +
                                 self._tab.Pos)
        return 0

    # NodeModel
    def Ports(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from btlib.Serialization.PortModel import PortModel
            obj = PortModel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NodeModel
    def PortsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NodeModel
    def PortsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0


def NodeModelStart(builder):
    builder.StartObject(3)


def NodeModelAddRegistrationName(builder, registrationName):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(registrationName), 0)


def NodeModelAddType(builder, type_):
    builder.PrependInt8Slot(1, type_, 0)


def NodeModelAddPorts(builder, ports):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(ports), 0)


def NodeModelStartPortsVector(
        builder, numElems):
    return builder.StartVector(4, numElems, 4)


def NodeModelEnd(builder):
    return builder.EndObject()
