# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Serialization


class NodeType(object):
    UNDEFINED = 0
    ACTION = 1
    CONDITION = 2
    CONTROL = 3
    DECORATOR = 4
    SUBTREE = 5
