# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Serialization

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()


class Timestamp(object):
    __slots__ = ['_tab']

    # Timestamp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Timestamp
    def UsecSinceEpoch(self):
        return self._tab.Get(
            flatbuffers.number_types.Uint64Flags,
            self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))


def CreateTimestamp(builder, usecSinceEpoch):
    builder.Prep(8, 8)
    builder.PrependUint64(usecSinceEpoch)
    return builder.Offset()
