# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see README (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: test

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every week at 22:00 on Sunday
    - cron: "0 22 * * 0"

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }}
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble, iron, rolling]
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.ROS_DISTRO }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: "ros-industrial/industrial_ci@master"
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          UPSTREAM_WORKSPACE: ${{ matrix.ROS_DISTRO == 'rolling' && 'github:ros-planning/navigation2#main -navigation2/nav2_amcl -navigation2/nav2_behavior_tree -navigation2/nav2_behaviors -navigation2/nav2_bringup -navigation2/nav2_bt_navigator -navigation2/nav2_collision_monitor -navigation2/nav2_constrained_smoother -navigation2/nav2_controller -navigation2/nav2_core -navigation2/nav2_costmap_2d -navigation2/nav2_docking -navigation2/nav2_dwb_controller -navigation2/nav2_graceful_controller -navigation2/nav2_lifecycle_manager -navigation2/nav2_map_server -navigation2/nav2_mppi_controller -navigation2/nav2_navfn_planner -navigation2/nav2_planner -navigation2/nav2_regulated_pure_pursuit_controller -navigation2/nav2_rotation_shim_controller -navigation2/nav2_rviz_plugins -navigation2/nav2_simple_commander -navigation2/nav2_smac_planner -navigation2/nav2_smoother -navigation2/nav2_system_tests -navigation2/nav2_theta_star_planner -navigation2/nav2_util -navigation2/nav2_velocity_smoother -navigation2/nav2_voxel_grid -navigation2/nav2_waypoint_follower -navigation2/navigation2 -navigation2/tools' || '' }}