name: lint
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every week at 20:00 on Sunday
    - cron: "0 20 * * 0"

jobs:
  ament_lint:
    name: Linting ${{ matrix.package-name }} with ${{ matrix.linter }}
    strategy:
      fail-fast: false
      matrix:
        package-name:
          - btlib
          - bt_live
          - bt_view
        linter: [flake8, pep257, xmllint]
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.package-name }}-${{ matrix.linter }}
      cancel-in-progress: true
    env:
      AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: 1
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@master
      - run: sudo pip install pydocstyle==6.1.1 # downgrade to fix https://github.com/ament/ament_lint/pull/428
      - uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}
          package-name: ${{ matrix.package-name }}
